# Uncomment the next line to define a global platform for your project
# platform :osx, '10.12'

target 'TransScreenShots' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TransScreenShots
pod 'AFNetworking', '~> 3.2.1'
  pod 'MJExtension', '~> 3.2.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'ReactiveObjC', '~> 3.1.1'
  pod 'MASShortcut', '~> 2.4.0'
  pod 'MASPreferences', '~> 1.3'
  pod 'CocoaLumberjack/Swift', '~> 3.6.0'
  pod 'SSZipArchive', '~> 2.2.2'
  pod 'Sparkle', '~> 1.22.0'

  target 'TransScreenShotsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TransScreenShotsUITests' do
    # Pods for testing
  end

end
